/*
	Script para crear tabla de contenidos
	17-09-2014
*/
CREATE TABLE IF NOT EXISTS `contenidos` (
 `id` INT(10) NOT NULL AUTO_INCREMENT,
 `pagina` VARCHAR(100) COLLATE utf8_bin DEFAULT '',
 `contenido` TEXT COLLATE utf8_bin, PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

INSERT INTO `contenidos` (`id`, `pagina`, `contenido`) VALUES
	(2, 'noticias', '<h3>Lanzaminento Red Hidroclimatológica</h3>\n\n<div><img alt="Presentacion.JPG" src="../img/Presentacion.JPG" style=" FLOAT:
LEFT; height:93px; width:150px" /></div>\n\n<div>\n<p>Presentación llevada a cabo el día 19 de Marzo de 2010</p>\n\n<p><br />\n<br />\n<br />\n<strong>Documento Adjunto:</strong><a href="pdf/Presentacion_Modo_de_compatibilidad.pdf" style=" TEXT-decoration: none" target="_blank"> Presentacion Modo de Compatibilidad&nbsp; </a></p>\n</div>\n'),
	(3, 'recursos_humanos', '<h3>Samuel Guzmán López</h3>\n	<ul>\n		<li>\n			Economista M.Sc\n		</li>\n		<li>\n			Docente Facultad de Ciencias Ambientales\n		</li>\n		<li>\n			sguzman@utp.edu.co\n		</li>\n	</ul>\n	<h3>Juan Mauricio Castaño Rojas</h3>\n	<ul>\n		<li>\n			Ing. Quimico M.Sc\n		</li>\n		<li>\n			Docente Asistente Facultad de Ciencias Ambientales\n		</li>\n		<li>\n			Área: Calidad de Agua - Ingeniería Ecologica\n		</li>\n		<li>\n			Modelación; Water Evaluation and Planning System (WEAP)\n		</li>\n		<li>\n			Jmc@utp.edu.co\n		</li>\n	</ul>\n	<h3>Carlos Andrés Sabas Ramírez</h3>\n	<ul>\n		<li>\n			Ing. Ambiental M.Sc\n		</li>\n		<li>\n			Docente Transitorio Facultad de Ciencias Ambientales.\n		</li>\n		<li>\n			Área: Quimica Ambiental - Hidroclimatología\n		</li>\n		<li>\n			Modelación; Water Evaluation and Planning System (WEAP) \n		</li>\n		<li>\n			candes@utp.edu.co\n		</li>\n	</ul>\n	<h3>Juan Camilo Berrio Carvajal</h3>\n	<ul>\n		<li>\n			Administrador Ambiental\n		</li>\n		<li>\n			Área: Hidroclimatologia.\n		</li>\n		<li>\n			Estudiante de Maestría en Instrumentación Física\n		</li>\n		<li>\n			jcberrio@utp.edu.co\n		</li>\n	</ul>\n	<h3>Santiago Cárdenas García</h3>\n	<ul>\n		<li>\n			Tecnólogo en Agua y Saneamiento\n		</li>\n		<li>\n			scardenasg@utp.edu.co\n		</li>\n	</ul>\n	<h3>Cristian Camilo Fernández Lopera</h3>\n	<ul>\n		<li>\n			Administrador Ambiental\n		</li>\n		<li>\n			ccfernandez@utp.edu.co\n		</li>\n	</ul>\n	<h3>Juliana Valencia Quintero</h3>\n	<ul>\n		<li>\n			Administradora Ambiental M.Sc\n		</li>\n		<li>\n			Área: Estudio de Oferta y Demanda\n		</li>\n		<li>\n			Modelación; Water Evaluation and Planning System (WEAP)\n		</li>\n		<li>\n			jvalencia@utp.edu.co \n		</li>\n	</ul>\n	<h3>Alberto Ramírez Acevedo</h3>\n	<ul>\n		<li>\n			Administrador Ambiental\n		</li>\n		<li>\n			Docente Transitorio Facultad de Ciencias Ambientales\n		</li>\n		<li>\n			Área: Sistemas de Información Geográfica\n		</li>\n		<li>\n			Modelación; Water Evaluation and planning System (WEAP)\n		</li>\n		<li>\n			arace@utp.edu.co\n		</li>\n	</ul>\n	<h3>Víctor Manuel Bermudez Marín</h3>\n	<div>\n		<ul>\n			<li>\n				Administrador Ambiental\n			</li>\n			<li>\n				Área: Hidroclimatología\n			</li>\n			<li>\n				vmbermudez@utp.edu.co\n			</li>\n		</ul>\n	</div>\n	<h3>Juan Pablo Aristizabal</h3>\n	<p></p>\n	<ul>\n		<li>\n			Tecnólogo en Manejo de Recursos Naturales\n		</li>\n		<li>\n			Auxiliar de Campo Monitoreo Hridoclimatológico\n		</li>\n	</ul>');
